### PR TITLE
Mrschmidt/parallelbuilds

### PR DESCRIPTION
**Pull request by samtstern**
cc @schmidt-sebastian the "Test All Packages" here should run on GAE

### CODE REVIEW

**Comment by samtstern** [comment]
@schmidt-sebastian nevermind the runner broke /shrug

**Comment by samtstern** [comment]
@schmidt-sebastian woohoo I got it to work!

**AppEngine**
https://github.com/samtstern/firebase-js-sdk/pull/5/checks?check_run_id=984768602
`yarn build` took `6m16s`

**GHA**
https://github.com/firebase/firebase-js-sdk/runs/981996342
`yarn build` took `12m10s`

**Comment by schmidt-sebastian** [comment]
Wow - that's pretty good. Firestore finished 200 seconds faster (we could even parallelize more builds, as the `exp` build is now done in one step).

**Comment by schmidt-sebastian** [comment]
Pushed a change to make lerna run in parallel.

**Pull request closed without merging**
